version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: invoice_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invoice_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoice -d invoice_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: invoice_app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - invoice_network
    # For development, uncomment these volumes:
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: invoice_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - invoice_network

volumes:
  postgres_data:
    driver: local

networks:
  invoice_network:
    driver: bridge